import type { Metadata } from "next";
import { Rubik } from 'next/font/google'
import "./globals.css";

// font
const rubik = Rubik({ subsets: ['latin'] })

// title
export const metadata: Metadata = {
  title: "AssetInvader",
  description: "Generated by AssetInvader",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html>
      <body className={rubik.className}>
        {children}
      </body>
    </html>
  );
}